trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    versionSpec: '18.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm run build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifact'

#- task: AzureRmWebAppDeployment@4
#  inputs:
#    ConnectionType: 'AzureRM'
#    azureSubscription: '<pipelineToken>'
#    appType: 'webAppLinux'
#    WebAppName: 'sem5pi-23-24-grupo59-be'
#    packageForLinux: '$(System.DefaultWorkingDirectory)/drop/*.zip'
#  displayName: 'Deploy to Azure Web App'